### ISSUE TITLE
How to open files?

### ISSUE THREAD

**Issue by rafaelmr2** [rgaiacs/ComicReader#1]
Hi,

I put cbz files in two medias (internal and SD) and when I click "open" I see only a blank screen. How this app works?

Thanks.

**Comment by rgaiacs** [comment]
Hi @rafaelmr2. Thanks for the feedback.

Could you provide more information like the device you are using and how do you install the app?

**Comment by rgaiacs** [comment]
@rafaelmr2 Could you take a look at #2? Try change the default storage and see if it work.

**Comment by rafaelmr2** [comment]
@r-gaia-cs , it works listing files. But when I click returns to blank screen.

I use Firefox OS 1.3 on GP Peak.

**Comment by rgaiacs** [comment]
> @r-gaia-cs , it works listing files. But when I click returns to blank screen.

OK. Could you send me at least one of the files you are trying to open? You
could send me the file or the link to my email (see my profile).

> I use Firefox OS 1.3 on GP Peak.

I tested with Firefox OS 2.1 at Hamachi and Flatfish. Don't know is some API has
change.

**Comment by rafaelmr2** [comment]
Sorry, this file : https://my.owndrive.com/public.php?service=files&t=1ef8be3be475f88abc0d7ef327af21b5

**Comment by rgaiacs** [comment]
@rafaelmr2 Thanks. Fix #3 should solve your problem. I will fix it during the week. Thanks again to report the bug and help debugging.

**Comment by rafaelmr2** [comment]
Thank you!!

**Comment by rgaiacs** [comment]
@rafaelmr2 I believe that the bug was fixed. I submitted a new version to Marketplace (will take a few days to it be approve) but if you like you can install the app using App Manager.

![sadman](https://cloud.githubusercontent.com/assets/1506457/3640576/77fa5d36-10a4-11e4-910d-c426dbe35847.png)

**Comment by rafaelmr2** [comment]
@r-gaia-cs yes, now works! thanks.
