### ISSUE TITLE
Pages are not sorted

### ISSUE THREAD

**Issue by rafaelmr2** [rgaiacs/ComicReader#4]
The pages of the comic book are out of order.

**Comment by rgaiacs** [comment]
Thanks for the report. I will work on this at the weekend.

**Comment by rgaiacs** [comment]
@rafaelmr2 I will need more time to find why this is happening. If you look at [this loop](https://github.com/r-gaia-cs/ComicReader/blob/master/js/app.js#L26https://github.com/r-gaia-cs/ComicReader/blob/master/js/app.js#L26) you will see that every page of the selected CBZ file is append (as they are sorted on it) to HTML page.

**Comment by rafaelmr2** [comment]
@r-gaia-cs, that's true. :)

**Comment by rgaiacs** [comment]
@rafaelmr2 Could you try the temporary solution?

**Comment by rafaelmr2** [comment]
@r-gaia-cs it's working now.

**Comment by rgaiacs** [comment]
@rafaelmr2 Thanks for check it. I will try find some time to work on #6 and #7. Please let me know of any change that you want to be made.
